version: 0.2
phases:
   install:
     runtime-versions:
         php: 8.1
         nodejs: 16
     
   pre_build:
     commands:
        #- cp .env.staging .env
         - aws s3 cp s3://elasticbeanstalk-us-east-1-424023781758/env.staging /.env
         - composer install
         - npm cache clean --force
         - npm install
        # - npm run dev
   build:
     commands:
         - php artisan migrate --force
         - php artisan db:seed
artifacts:
   files:
         - '**/*'
   name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
   upload-artifacts: yes
   logs: yes